### ISSUE TITLE
!!!

### ISSUE THREAD

**Issue by melonges** [dearcpp/QMLTemplate#1]
**выучите плюсы в начале чтобы такое не писать. Позор!!!**

**Comment by beryll1um** [comment]
Looking at your projects, you can really tell that you have the necessary competence. (https://github.com/mellonges/terminal-fps-checker)

Since you did not bother to give any specific recommendations, we will consider this ticket closed.

**Comment by melonges** [comment]
> Looking at your projects, you can really tell that you have the necessary competence. (https://github.com/mellonges/terminal-fps-checker)
> 
> Since you did not bother to give any specific recommendations, we will consider this ticket closed.

отвечать на английском на русский это гениально.
а если видите проблему в моем [fps checker](https://github.com/mellonges/terminal-fps-checker), то готов принять от Вас **issue** или **pull request**.

_С уважением, performance optimization engineer from Intel_
